name: Atualizar README com Alterações

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY_DEV }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H stage.evedi.io >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa bitnami@stage.evedi.io "echo 'SSH setup successfully'"
        env:
          SERVER_SSH_KEY_DEV: ${{ secrets.SERVER_SSH_KEY_DEV }}

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa bitnami@stage.evedi.io << EOF
            cd docker-server-geosis
            git pull
            sudo docker-compose build node
            sudo docker-compose up -d --no-deps --force-recreate node
            exit
          EOF
