version: '3'

services:
  edi_dash_api:
    container_name: api
    env_file: .env
    build: 
      context: .
      dockerfile: dockerfile
    image: edi_dash_image
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - $CLIENT_PORT:$SERVER_PORT
    networks:
      - edi_dash_network

networks:
  edi_dash_network:
    name: edi_dash_network
    driver: bridge