name: Atualizar README com Alterações

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H stage.evedi.io >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa bitnami@stage.evedi.io "echo 'SSH setup successfully'"
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa bitnami@stage.evedi.io << EOF
            cd ..
            cd Flutter-website-Aaron
            sudo git pull
            sudo docker-compose up --build -d
            exit
          EOF
